# SonarQube configuration
sonar.organization=eloise04
sonar.projectKey=eloise04_flowboard
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude coverage files from analysis
sonar.exclusions=coverage/**/*
sonar.test.exclusions=coverage/**/*

# Quality Gate settings for new code
sonar.qualitygate.wait=true
sonar.newcode.period=previous_version